# Generated by Django 3.2.7 on 2021-10-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0010_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='photos'),
        ),
    ]
