# Generated by Django 3.2.7 on 2021-10-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0014_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.FileField(default='bal.jpg', null=True, upload_to='photos'),
        ),
    ]
