# Generated by Django 3.2.7 on 2021-10-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0015_alter_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.FileField(blank=True, default='bal.jpg', null=True, upload_to='photos'),
        ),
    ]
